-- menu_descriptions.sql — one line per dish, from the kitchen's own Zomato listing.
-- Generated 2026-09-12 from Menu-data.xlsx. Safe to re-run: plain UPDATEs by item id,
-- and ids are identical on production (see menu_snapshot.sql).

UPDATE menu_items SET description = 'Desi Ghee Preparation · Hara Bhara kebab is a popular North Indian vegetarian snack made from spinach, green peas, and potatoes shaped into patties and pan- or shallow-fried.' WHERE id = 22;
UPDATE menu_items SET description = 'Crispy Chilli Corn is a popular Indo-Chinese appetizer made from sweet corn kernels that are deep-fried until golden and crunchy, then tossed in spicy and tangy seasonings.' WHERE id = 23;
UPDATE menu_items SET description = 'A spring roll is a filled, rolled appetizer made by wrapping vegetables or other ingredients in a thin wrapper, then serving it fried until crisp.' WHERE id = 24;
UPDATE menu_items SET description = 'Crispy fried potato fingers tossed in a spicy garlic-chilli sauce with bold Indo-Chinese flavors.' WHERE id = 25;
UPDATE menu_items SET description = 'Crispy potato fingers tossed in a delicious sweet and spicy honey chilli glaze with bold flavors.' WHERE id = 26;
UPDATE menu_items SET description = 'Veg Manchurian Dry features crispy fried vegetable balls tossed in a tangy, spicy Indo-Chinese sauce.' WHERE id = 27;
UPDATE menu_items SET description = 'Soft paneer cubes tossed in a bold hot garlic sauce with red chilli flakes, crunchy veggies and aromatic spices.' WHERE id = 29;
UPDATE menu_items SET description = 'A perfect balance of crunch, sweetness, and heat that makes every bite irresistibly delicious; crispy paneer cubes tossed in a sweet and spicy honey chilli glaze with bold savory flavors.' WHERE id = 30;
UPDATE menu_items SET description = 'Tandoori Aloo is a North Indian appetizer featuring baby potatoes marinated in spiced yogurt and roasted in a traditional clay oven known as a tandoor.' WHERE id = 31;
UPDATE menu_items SET description = 'Tandoori Gobi is an Indian tandoor-style appetizer made from cauliflower florets marinated in spiced yogurt and roasted at high heat.' WHERE id = 32;
UPDATE menu_items SET description = 'Paneer Tikka is a popular Indian tandoori appetizer made by marinating cubes of paneer (fresh cheese) in spiced yogurt and roasting them in a tandoor or grill.' WHERE id = 33;
UPDATE menu_items SET description = 'A bold, restaurant-style starter with 8 juicy pieces—perfect for stoking your appetite with that signature pickle-flavor kick.' WHERE id = 34;
UPDATE menu_items SET description = 'Soft paneer cubes marinated in rich cream, and aromatic spices, grilled to perfection.' WHERE id = 35;
UPDATE menu_items SET description = 'Vegetable noodles are a popular Indo-Chinese stir-fried noodle dish made with boiled noodles, mixed vegetables, and savory sauces.' WHERE id = 36;
UPDATE menu_items SET description = 'Noodles tossed in a fiery blend of fresh garlic, red chillies, and savory sauces for the perfect spicy kick.' WHERE id = 37;
UPDATE menu_items SET description = 'Singapore Noodles is a stir-fried noodles dish commonly found in Chinese restaurants worldwide, especially in Western countries.' WHERE id = 38;
UPDATE menu_items SET description = 'Vegetable Fried Rice is a popular Indo-Chinese stir-fried rice dish made with cooked rice, assorted vegetables, and Asian seasonings.' WHERE id = 39;
UPDATE menu_items SET description = 'Authentic chilli garlic noodles doesn\'t have vegetables, kindly write or select with or without vegetables.' WHERE id = 40;
UPDATE menu_items SET description = 'Indo-Chinese fried rice tossed with crispy golden-brown burnt garlic, mixed veggies (carrots, beans, capsicum, spring onions), soy sauce, vinegar, and pepper for a smoky, aromatic kick.' WHERE id = 41;
UPDATE menu_items SET description = 'A vegetable grilled sandwich is a toasted or pressed sandwich filled with assorted vegetables, often spiced or seasoned, and cooked until the bread is crisp and golden.' WHERE id = 42;
UPDATE menu_items SET description = 'Pair of Breads packed with sweet corn, fresh veggies, and flavorful seasonings, grilled until perfectly crisp.' WHERE id = 43;
UPDATE menu_items SET description = 'Stuffed with flavorful Samosa Style masala potatoes, fresh seasonings, and grilled until perfectly crisp and golden.' WHERE id = 44;
UPDATE menu_items SET description = 'Crispy, butter-toasted bread with gooey melted cheese and a tangy-spicy kick—perfect street-style snack, stuffed with a spicy mix of grated processed & mozzarella cheese, chopped capsicum, onion,…' WHERE id = 45;
UPDATE menu_items SET description = 'A Paneer grilled sandwich with hariyali marinade is an Indian-style vegetarian sandwich featuring marinated paneer (Indian cottage cheese) grilled between slices of bread.' WHERE id = 46;
UPDATE menu_items SET description = 'A tandoori paneer grilled sandwich is an Indian-style fusion snack that combines smoky, spiced cottage cheese (paneer) with toasted bread.' WHERE id = 47;
UPDATE menu_items SET description = 'Crispy grilled sandwich stuffed with tangy Achari-spiced paneer and fresh veggies, wrapped in soft golden bread.' WHERE id = 48;
UPDATE menu_items SET description = 'Buttered bread slices layered with spicy-green chutney and fresh veggies—boiled potatoes, beetroot, cucumber, tomatoes, onions, and sometimes capsicum—then grilled to golden perfection.' WHERE id = 49;
UPDATE menu_items SET description = 'A Potato Wrap (Spicy potato fusion wrap) is a handheld meal featuring seasoned or spiced potato fillings rolled in a flatbread such as tortilla, roti, or pita.' WHERE id = 50;
UPDATE menu_items SET description = 'A Potato Wrap (Spicy Achari Fusion) is a contemporary Indian-inspired street food wrap combining tangy pickled (“achari”) flavors with spiced mashed or roasted potatoes.' WHERE id = 51;
UPDATE menu_items SET description = 'Crispy chilli potatoes wrapped in a soft tawa paratha with fresh veggies and zesty sauces.' WHERE id = 52;
UPDATE menu_items SET description = 'A wholesome, spicy, and satisfying wrap packed with delicious street-style flavors in every bite. masala corn wrapped in a paratha with fresh veggies and signature spices.' WHERE id = 53;
UPDATE menu_items SET description = 'Peri Peri Paneer Tikka Fusion Wrap variation combines Indian tikka spices with the tangy heat of peri peri sauce, offering a bold, flavorful handheld meal. smoky paneer tikka wrapped in a…' WHERE id = 54;
UPDATE menu_items SET description = 'A Paneer Wrap, often styled as a Tandoori Paneer Tikka Wrap, is an Indian-inspired street and café food featuring marinated paneer (Indian cottage cheese) grilled with spices and wrapped in flatbread.' WHERE id = 55;
UPDATE menu_items SET description = 'A flavorful street-food style wrap that delivers smoky, spicy, and tangy flavors in every bite—perfect for a quick, satisfying meal.' WHERE id = 56;
UPDATE menu_items SET description = 'Spicy chilli paneer wrapped in a soft tortilla with crunchy veggies and flavorful sauces.' WHERE id = 57;
UPDATE menu_items SET description = 'Crispy golden potato fries perfectly seasoned and fried to deliver the ultimate crunchy bite.' WHERE id = 58;
UPDATE menu_items SET description = 'Corn kernels simply fried and salted or pepper or chaat masala coated.' WHERE id = 59;
UPDATE menu_items SET description = 'Steamed corn is a light snack dish made by cooking fresh or frozen corn kernels with steam until tender and naturally sweet.' WHERE id = 60;
UPDATE menu_items SET description = 'Onion Pakora (also called Onion Pakoda, Pyaz ke Pakode, or Kanda Bhaji) is a deep-fried Indian fritter made with sliced onions coated in a spiced gram flour (besan) batter.' WHERE id = 61;
UPDATE menu_items SET description = 'Fresh cauliflower florets coated in spiced gram flour batter and fried until perfectly crispy.' WHERE id = 62;
UPDATE menu_items SET description = 'Soft paneer slices coated in spiced gram flour batter and fried until perfectly golden and crispy.' WHERE id = 63;
UPDATE menu_items SET description = 'Crispy golden rolls stuffed with creamy hung curd, aromatic spices, and a rich flavorful filling.' WHERE id = 64;
UPDATE menu_items SET description = 'Uttapam is a traditional South Indian savory pancake made from a fermented batter of rice and lentils.' WHERE id = 76;
UPDATE menu_items SET description = 'Soft, fluffy uttapam topped with fresh onions and cooked with authentic South Indian flavors.' WHERE id = 77;
UPDATE menu_items SET description = 'Soft, fluffy uttapam topped with fresh tomatoes, onions, and authentic South Indian seasonings.' WHERE id = 78;
UPDATE menu_items SET description = 'Soft, fluffy uttapam topped with fresh vegetables and cooked to perfection with authentic South Indian flavors.' WHERE id = 79;
UPDATE menu_items SET description = 'Sambar is a traditional South Indian lentil and vegetable stew flavored with tamarind and aromatic spices.' WHERE id = 80;
UPDATE menu_items SET description = 'The perfect creamy side that adds authentic flavor and balance to your favorite South Indian dishes.' WHERE id = 81;
UPDATE menu_items SET description = 'Tomato Chutney is a South Indian condiment made primarily from ripe tomatoes, spices, and aromatics.' WHERE id = 82;
UPDATE menu_items SET description = 'A refreshing blend of fresh coriander, mint, green chillies, imli and aromatic spices for a burst of flavor.' WHERE id = 83;
UPDATE menu_items SET description = 'Podi, also known as “gunpowder,” is a dry, spiced lentil powder condiment from South India.' WHERE id = 84;
UPDATE menu_items SET description = 'Serves 1, 2 Pieces' WHERE id = 85;
UPDATE menu_items SET description = 'Crispy golden dosa prepared to perfection with a light texture and authentic South Indian flavors.' WHERE id = 65;
UPDATE menu_items SET description = 'Crispy golden dosa filled with flavorful spiced potato masala and served with classic accompaniments.' WHERE id = 66;
UPDATE menu_items SET description = 'Crispy golden dosa layered with flavorful podi spice mix and aromatic South Indian seasonings.' WHERE id = 67;
UPDATE menu_items SET description = 'Crispy golden dosa topped with fresh onions and perfectly cooked for a flavorful crunchy bite.' WHERE id = 68;
UPDATE menu_items SET description = 'Crispy golden dosa layered with fresh onions and stuffed with flavorful spiced potato masala.' WHERE id = 69;
UPDATE menu_items SET description = 'Crispy dosa layered with spicy Mysore chutney and stuffed with flavorful potato masala for a bold taste.' WHERE id = 70;
UPDATE menu_items SET description = 'Crispy golden dosa stuffed with flavorful paneer masala and perfectly balanced aromatic spices.' WHERE id = 71;
UPDATE menu_items SET description = 'Schezwan Dosa is a popular Indo-Chinese fusion dish that blends South Indian dosa traditions with spicy Schezwan sauce flavors.' WHERE id = 72;
UPDATE menu_items SET description = 'Crispy golden dosa stuffed with sweet corn, flavorful spices, and a delicious savory filling.' WHERE id = 73;
UPDATE menu_items SET description = 'Thin, crispy semolina dosa cooked to golden perfection with a light and crunchy texture.' WHERE id = 74;
UPDATE menu_items SET description = 'Crispy semolina dosa filled with spiced potato masala, crafted for a light and flavorful crunch.' WHERE id = 75;
UPDATE menu_items SET description = 'Soft paneer cubes cooked in a rich creamy gravy infused with aromatic spices and royal flavors.' WHERE id = 96;
UPDATE menu_items SET description = 'Soft paneer cubes simmered in a rich buttery tomato gravy blended with cream and aromatic spices.' WHERE id = 102;
UPDATE menu_items SET description = 'Malai kofta is a rich North Indian curry made of deep-fried dumplings (koftas) crafted from paneer (Indian cottage cheese), potatoes, and sometimes nuts or dried fruit, served in a creamy, spiced…' WHERE id = 97;
UPDATE menu_items SET description = 'Smoky paneer tikka pieces simmered in a rich creamy(yogurt) gravy blended with aromatic Indian spices.' WHERE id = 101;
UPDATE menu_items SET description = 'Kadhai Paneer is a popular North Indian curry featuring soft paneer cubes and bell peppers cooked in a spicy, tangy tomato-onion gravy with crushed spices.' WHERE id = 104;
UPDATE menu_items SET description = 'Soft paneer cubes and green peas simmered in a rich tomato-based gravy with aromatic Indian spices.' WHERE id = 103;
UPDATE menu_items SET description = 'Soft paneer cubes cooked with double onions, rich gravy, and aromatic Indian spices for bold flavor.' WHERE id = 99;
UPDATE menu_items SET description = 'Shahi Paneer is a classic North Indian curry featuring soft cubes of paneer (fresh Indian cheese) in a rich, creamy sauce made from tomatoes, onions, nuts, cream, and aromatic spices.' WHERE id = 98;
UPDATE menu_items SET description = 'Paneer Handi is a North Indian curry made with cubes of paneer (Indian cottage cheese) simmered in a creamy, spiced tomato–onion–cashew gravy with diced capsicum.' WHERE id = 100;
UPDATE menu_items SET description = 'Crispy vegetable dumplings simmered in a rich, tangy Manchurian sauce with bold flavors.' WHERE id = 105;
UPDATE menu_items SET description = 'Crispy paneer tossed in a rich, tangy Manchurian sauce with fresh veggies and bold flavors.' WHERE id = 106;
UPDATE menu_items SET description = 'Soft paneer cubes cooked in a rich, spicy garlic-chilli sauce with crunchy veggies and bold flavors.' WHERE id = 107;
UPDATE menu_items SET description = 'Dal Fry is a traditional Indian Yellow lentil (Tuur/Arhar) made by simmering cooked lentils with a fragrant tempering of spices sautéed in ghee or oil.' WHERE id = 86;
UPDATE menu_items SET description = 'Dal Tadka is a comforting North Indian dish of creamy yellow lentils (Tuur/Arhar) tempered with aromatic spices, garlic, and ghee.' WHERE id = 87;
UPDATE menu_items SET description = 'Dal Handi is a traditional North Indian lentil curry known for its rich, smoky flavor and creamy texture.' WHERE id = 88;
UPDATE menu_items SET description = 'Dal Makhani is a rich North Indian lentil curry made primarily from whole black gram (urad dal) and red kidney beans (rajma), slow-cooked with butter, cream, and tomatoes.' WHERE id = 89;
UPDATE menu_items SET description = 'A flavorful medley of fresh vegetables sautéed with aromatic spices for a perfectly balanced desi taste.' WHERE id = 95;
UPDATE menu_items SET description = 'A classic Punjabi dry sabzi of soft potatoes and fresh green peas cooked with cumin, turmeric, red chili, coriander, garam masala, and tangy amchur (mango powder).' WHERE id = 90;
UPDATE menu_items SET description = 'Soft potato and green peas simmered in a spiced onion tomato gravy with cumin, coriander, turmeric, garam masala and fresh ginger garlic flavors.' WHERE id = 91;
UPDATE menu_items SET description = 'A classic North Indian dry dish of tender potatoes and cauliflower cooked with cumin, turmeric, green chillies and aromatic Punjabi spices.' WHERE id = 92;
UPDATE menu_items SET description = 'Tender potatoes and cauliflower florets cooked in a rich, creamy onion tomato cashew gravy with aromatic Punjabi spices like turmeric, coriander and garam masala.' WHERE id = 93;
UPDATE menu_items SET description = 'Flaky layered paratha baked in a tandoor for a smoky aroma and perfectly crisp buttery texture.' WHERE id = 108;
UPDATE menu_items SET description = 'Soft, freshly baked Indian bread with a light fluffy texture and delicious tandoor-cooked flavor.' WHERE id = 109;
UPDATE menu_items SET description = 'Tandoori Roti is an unleavened Indian flatbread made primarily from whole wheat flour (atta) and traditionally baked in a cylindrical clay oven called a tandoor.' WHERE id = 110;
UPDATE menu_items SET description = 'Brushed generously with melted butter before serving—golden, slightly bubbly, and perfectly paired with Paneer Curry or any thick gravy dish.' WHERE id = 111;
UPDATE menu_items SET description = 'A classic Indian bread that\'s perfect with curries like Paneer Butter Masala or Dal Makhani—lightly charred, buttery, and irresistibly aromatic.' WHERE id = 112;
UPDATE menu_items SET description = 'Garlic naan is a soft, leavened Indian flatbread infused with garlic and traditionally baked in a tandoor, or clay oven.' WHERE id = 113;
UPDATE menu_items SET description = 'A restaurant-style naan that\'s perfect for mopping up curries—golden, slightly charred, and irresistibly aromatic.' WHERE id = 114;
UPDATE menu_items SET description = 'Roti is a traditional Indian unleavened flatbread made from whole wheat flour, known as atta.' WHERE id = 115;
UPDATE menu_items SET description = 'A paratha is a type of Indian pan-fried flatbread traditionally made from whole wheat flour and ghee or oil.' WHERE id = 116;
UPDATE menu_items SET description = 'Laccha Paratha is a layered North Indian flatbread known for its flaky, crisp exterior and soft inner folds.' WHERE id = 117;
UPDATE menu_items SET description = 'Simple flat bread filled or stuffed generously with potato minced with some Indian Masala, fresh herbs and aromatics served as a common Indian Breakfast or an early supper dish.' WHERE id = 118;
UPDATE menu_items SET description = 'An Indian flatbread created using wheat floor stuffed with finely chopped onions, green chilli and some aromatic masala.' WHERE id = 119;
UPDATE menu_items SET description = 'Flatbread stuffed with Gobhi, chillies, coriander, and aromatics.' WHERE id = 120;
UPDATE menu_items SET description = 'Steamed rice is a simple, staple dish made by cooking rice grains in water or steam until tender and fluffy.' WHERE id = 122;
UPDATE menu_items SET description = 'Fragrant basmati rice tempered with roasted cumin and subtle spices for a simple yet flavorful experience.' WHERE id = 123;
UPDATE menu_items SET description = 'Vegetable Pulao (also called Veg Pulao or Pulav) is an Indian mixed vegetable rice dish made by cooking fragrant basmati rice with assorted vegetables, whole spices, and herbs.' WHERE id = 124;
UPDATE menu_items SET description = 'Fragrant basmati rice cooked with green peas, whole spices, and aromatic flavors for a wholesome meal.' WHERE id = 125;
UPDATE menu_items SET description = 'Aromatic basmati rice cooked with dry fruits, saffron, and mild spices for a rich royal flavor.' WHERE id = 126;
UPDATE menu_items SET description = 'Vegetable biryani is a spiced rice dish from the Indian subcontinent prepared with fragrant basmati rice, mixed vegetables, herbs, and aromatic spices.' WHERE id = 127;
UPDATE menu_items SET description = 'Cucumber, Tomato, Onion, sometimes more (carrots, beat, radish etc) topped with green chillies and lemon.' WHERE id = 128;
UPDATE menu_items SET description = '1 Dry Veg, 1 Semi-Dry Veg, Dal Tadka, 4 Roti, Rice, Salad. Hajmola (Complimentary Sweet and sour Pickled Mango)' WHERE id = 129;
UPDATE menu_items SET description = '1 Paneer Dish, 1 Dry/Semi Dry, Dal Tadka, 4 Roti, Salad. Hajmola(Complimentary Sweet and sour pickled Mango)' WHERE id = 130;
UPDATE menu_items SET description = 'Any Noodles/Rice, with one gravy item and chinese salad.' WHERE id = 131;
UPDATE menu_items SET description = 'Noodles/Rice with 1 dry, and 1 gravy item, chinese salad.' WHERE id = 132;
UPDATE menu_items SET description = 'Crispy paneer cubes wok-tossed with onion, capsicum, spicy chillies, garlic, and flavorful sauces for a perfect punch of flavor.' WHERE id = 28;
UPDATE menu_items SET description = 'Kadai vegetable, also known as veg kadai, is a North Indian mixed vegetable curry prepared in a kadai, a deep, wok like pan.' WHERE id = 94;

SELECT COUNT(*) AS items_with_description FROM menu_items WHERE description IS NOT NULL AND description <> '';
