import { useAuth } from '../../shared/hooks/useAuth';
import { LegalPage, Clause, Fact } from './LegalPage';
import { business } from './businessDetails';

/**
 * What this policy says is what the code actually does. The data list below
 * was taken from the schema and the API, not from a template: we hold a name,
 * a phone number, delivery addresses, order history, a hashed PIN and push
 * tokens, and nothing else.
 */
export function Privacy() {
  const { settings } = useAuth();
  const name = settings?.kitchen_name ?? 'Vaatsalya Kitchens';
  const email = business.contactEmail;
  const phone = settings?.kitchen_phone_display || business.contactPhone;

  return (
    <LegalPage
      title="Privacy Policy"
      intro={<p>How {name} collects, uses and protects your personal information when you order from us.</p>}
    >
      <Clause heading="Who we are">
        <p>
          This website and app are operated by <Fact value={business.legalName} label="registered business name" />, a{' '}
          <Fact value={business.entityType} label="entity type" /> trading as {name}, at{' '}
          <Fact value={business.registeredAddress} label="registered address" />. In this policy &ldquo;we&rdquo;,
          &ldquo;us&rdquo; and &ldquo;our&rdquo; mean that business, and &ldquo;you&rdquo; means the person placing an
          order.
        </p>
      </Clause>

      <Clause heading="What we collect">
        <p>We collect only what is needed to take an order and deliver it:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li><strong>Your name and mobile number</strong> — to identify your account and to contact you about an order.</li>
          <li><strong>Delivery addresses</strong> you save, including map coordinates if you pick a location — to deliver to you.</li>
          <li><strong>Your order history</strong> — items, quantities, amounts and order status.</li>
          <li><strong>A PIN you set</strong>, which we store only as a one-way cryptographic hash. We cannot read it back.</li>
          <li><strong>Notification permission and a device token</strong>, if you allow order notifications — to tell you when your order is confirmed, on its way, or delivered.</li>
          <li><strong>Basic technical logs</strong> generated by our web server, such as request times and error records.</li>
        </ul>
        <p>
          We do <strong>not</strong> collect your date of birth, your gender, your background location, your contacts,
          your photos, or any biometric data.
        </p>
      </Clause>

      <Clause heading="Payment information">
        <p>
          We do not collect or store your card, UPI or bank details. When online payment is enabled it is handled
          entirely by a PCI-DSS compliant payment gateway, and we receive only the result of the payment and a
          reference number — never your card number, CVV, UPI PIN or bank credentials.
        </p>
      </Clause>

      <Clause heading="Why we use it">
        <p>
          We use your information to take, prepare, deliver and bill your order, to send you order updates, to keep a
          record of past orders in your account, to answer your questions, and to meet our legal and tax obligations.
          We rely on the performance of our contract with you, and on our legal obligations, to do this. We do not sell
          your personal information, and we do not share it for anyone else&rsquo;s advertising.
        </p>
      </Clause>

      <Clause heading="Who we share it with">
        <p>We share the minimum necessary, and only with:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li><strong>Our own kitchen and delivery staff</strong>, who see your name, phone number, address and order so they can prepare and deliver it.</li>
          <li><strong>Google Firebase Cloud Messaging</strong>, which delivers order notifications to your device if you have allowed them.</li>
          <li><strong>Our hosting provider</strong>, which stores the site and its database on our behalf.</li>
          <li><strong>A payment gateway</strong>, once online payment is enabled, to process your payment.</li>
          <li><strong>Authorities</strong>, where the law requires us to disclose information.</li>
        </ul>
      </Clause>

      <Clause heading="Cookies and browser storage">
        <p>
          We do not use advertising or tracking cookies, and we do not run third-party analytics that profile you. To
          keep you signed in, we store a sign-in token in your browser&rsquo;s own storage on your device. Signing out,
          or clearing your browser data, removes it.
        </p>
      </Clause>

      <Clause heading="How long we keep it">
        <p>
          We keep your account and order history for as long as your account is open, and after that only for as long
          as tax and accounting law requires us to keep records of a sale. Sign-in tokens expire on their own, and a
          notification token is deleted as soon as a device stops accepting notifications.
        </p>
      </Clause>

      <Clause heading="How we protect it">
        <p>
          Your PIN is stored only as a hash. Signing in uses expiring tokens rather than a permanent password, and both
          the website and the app talk to our server over an encrypted HTTPS connection. Access to the admin panel is
          limited to our staff accounts. No system is perfectly secure, but we do not hold the data that would be most
          damaging to lose: there are no card details and no readable PIN in our records.
        </p>
      </Clause>

      <Clause heading="Your rights">
        <p>
          You may ask us for a copy of the personal information we hold about you, ask us to correct it, or ask us to
          delete your account and its data. You can edit your saved addresses yourself in your account at any time. To
          make any of these requests, contact us using the details below and we will respond within 30 days. Deleting
          your account does not remove invoice records that we are legally required to retain.
        </p>
      </Clause>

      <Clause heading="Children">
        <p>
          Our service is not directed at children under 18, and we do not knowingly create accounts for them. If you
          believe a child has given us personal information, contact us and we will delete it.
        </p>
      </Clause>

      <Clause heading="Changes to this policy">
        <p>
          If we change this policy we will post the new version on this page and update the effective date at the top.
          Please check back from time to time.
        </p>
      </Clause>

      <Clause heading="Grievance Officer">
        <p>
          In accordance with the Information Technology Act, 2000 and the rules made under it, the contact details of
          our Grievance Officer are:
        </p>
        <p className="rounded-xl border border-cream-200 bg-cream-50 p-4">
          <strong><Fact value={business.grievanceOfficerName} label="officer name" /></strong>
          <br />
          Email: <Fact value={business.grievanceOfficerEmail} label="officer email" />
          <br />
          Phone: <Fact value={business.grievanceOfficerPhone} label="officer phone" />
        </p>
      </Clause>

      <Clause heading="Contact us">
        <p>
          {name}
          {email && (
            <>
              <br />
              Email: <a className="link-quiet" href={`mailto:${email}`}>{email}</a>
            </>
          )}
          {phone && (
            <>
              <br />
              Phone: <a className="link-quiet" href={`tel:+${settings?.kitchen_whatsapp}`}>{phone}</a>
            </>
          )}
          <br />
          Address: <Fact value={settings?.kitchen_address || business.registeredAddress} label="business address" />
        </p>
      </Clause>
    </LegalPage>
  );
}
